"""
config.py — Adversarial Training for Pipeline Mask-and-Fill
============================================================
Supports two combos:
  Combo 1: RoBERTa NER  +  DeBERTa-MLM filler  (fine-tune the DeBERTa-MLM filler)
  Combo 2: RoBERTa NER  +  BART seq2seq filler  (fine-tune the BART filler)

Both fillers are fine-tuned against a frozen BART-base inverter using the
adversarial loss:

    L_total = ALPHA · L₁  −  LAMBDA_ADV · L₂

  L₁ = quality anchor (CE of filler output vs gold anonymized text)
  L₂ = inverter entity recovery loss (negated → fool the inverter)

Gradient paths
--------------
  Combo 2 (BART filler — exact):
      filler logits (B,T,50265)  →  soft_embs = softmax(logits/T) @ inv.embed_W
      →  frozen BART inverter encoder  →  L₂
      Gradient flows cleanly (shared BART vocab on both sides).

  Combo 1 (DeBERTa-MLM filler — approximation):
      DeBERTa encoder last_hidden_state (B,T,768)
      →  used directly as inputs_embeds for frozen BART inverter encoder
      →  L₂
      Gradient flows through the hidden states (same dim=768 on both sides).
      The embedding spaces are not perfectly aligned but provide a valid
      training signal; with a small LR the filler learns to produce more
      diverse, less predictable entity replacements.
"""

import os

BASE_DIR    = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(BASE_DIR)

# ── Dataset files (generated by create_dataset.py) ─────────────────────────
ADV_TRAIN_FILE = os.path.join(BASE_DIR, "output", "adv_train.jsonl")
ADV_EVAL_FILE  = os.path.join(BASE_DIR, "output", "adv_eval.jsonl")
# HuggingFace dataset repo — used as fallback when local files are missing.
HF_DATASET_REPO = "JALAPENO11/pii-adversarial-pipeline-dataset"

# ── Models ─────────────────────────────────────────────────────────────────
# Combo 1 filler (DeBERTa-MLM) - will be fine-tuned
COMBO1_FILLER_ID   = "Xyren2005/pii-ner-filler_deberta-filler"
# Combo 2 filler (BART seq2seq) - will be fine-tuned
COMBO2_FILLER_ID   = "Xyren2005/pii-ner-filler_bart-base"
# Combo 1 inverter (BART, frozen adversary)
COMBO1_INVERTER_ID = "JALAPENO11/pii-inverter-roberta-deberta"
# Combo 2 inverter (BART, frozen adversary)
COMBO2_INVERTER_ID = "JALAPENO11/pii-inverter-roberta-bart"

# ── HuggingFace output repos (hardened models) ─────────────────────────────
COMBO1_OUTPUT_REPO = "JALAPENO11/pii-filler-deberta-adv-hardened"
COMBO2_OUTPUT_REPO = "JALAPENO11/pii-filler-bart-adv-hardened"

# ── Checkpoint dirs (local) ─────────────────────────────────────────────────
COMBO1_CKPT_DIR = os.path.join(BASE_DIR, "checkpoints", "combo1")
COMBO2_CKPT_DIR = os.path.join(BASE_DIR, "checkpoints", "combo2")

LOGS_DIR    = os.path.join(BASE_DIR, "logs")
RESULTS_DIR = os.path.join(BASE_DIR, "results")

# ── Combined loss weights ───────────────────────────────────────────────────
# L_total = ALPHA · L₁  −  LAMBDA_ADV · L₂
# Start conservative: raise LAMBDA_ADV if quality stays good after inspection.
ALPHA      = 1.0
LAMBDA_ADV = 0.5

# Softmax temperature applied to filler logits before the soft-embedding matmul.
# 1.0 = standard; increase slightly (e.g. 1.5) to smooth gradients through inverter.
SOFT_TEMP = 1.0

# ── Sequence lengths ────────────────────────────────────────────────────────
MAX_INPUT_LENGTH  = 96    # masked_mlm / masked_s2s → filler encoder
MAX_TARGET_LENGTH = 96    # anonymized / original    → decoder labels

# ── Training hyperparameters ────────────────────────────────────────────────
NUM_EPOCHS       = 3
WEIGHT_DECAY     = 0.01
LABEL_SMOOTHING  = 0.1
MAX_GRAD_NORM    = 1.0
NUM_WORKERS      = 0      # 0 = main process; avoids pinned-memory OOM on small GPUs

# Combo-specific batch sizes & LRs
# Combo 1 (DeBERTa-MLM, encoder-only): model is smaller per-param but
#   gradient path is approximate → use slightly smaller LR.
COMBO1_BATCH_SIZE       = 2
COMBO1_EVAL_BATCH_SIZE  = 2
COMBO1_GRAD_ACCUM_STEPS = 8     # effective batch = 2×8 = 16
COMBO1_LEARNING_RATE    = 5e-6
COMBO1_WARMUP_STEPS     = 100

# Combo 2 (BART filler): exact soft-embedding path → standard LR.
COMBO2_BATCH_SIZE       = 1
COMBO2_EVAL_BATCH_SIZE  = 1
COMBO2_GRAD_ACCUM_STEPS = 16    # effective batch = 1×16 = 16
COMBO2_LEARNING_RATE    = 1e-5
COMBO2_WARMUP_STEPS     = 100

# ── Eval / checkpoint schedule ──────────────────────────────────────────────
EVAL_STEPS    = 500
LOGGING_STEPS = 50

# ── Kaggle-specific paths (used when training on Kaggle) ────────────────────
KAGGLE_CKPT_DIR = "/kaggle/working/checkpoints"
